word = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(word)))
print('Só tem espaços? {}'.format(word.isspace()))
print('É um número? {}'.format(word.isnumeric()))
print('É alfabético? {}'.format(word.isalpha()))
print('é alfanumérico? {}'.format(word.isalnum()))
print('Está em maiúsculas? {}'.format(word.isupper()))
print('Está em minúsculas? {}'.format(word.islower()))
print('Está capitalizada? {}'.format(word.istitle()))
