tabelaTimes = ('Internacional', 'Flamengo', 'Atlético-MG', 'São Paulo', 'Fluminense', 'Palmeiras', 'Grêmio', 'Corinthians', 'Bragantino', 'Athletico-PR', 'Santos', 'Ceará', 'Atlético-GO', 'Fortaleza', 'Vasco', 'Bahia', 'Sport', 'Goiás', 'Coritiba', 'Botafogo')
print('Tabela do Brasileirão — SÉRIE A 2020/2021')
print('=-='*20)
print(f'Lista dos times: {tabelaTimes}')
print(f'Os 5 primeiros colocados são: {tabelaTimes[0:5]}')
print('=-='*20)
print(f'Os 4 últimos colocados são: {tabelaTimes[16:]}')
print('=-='*20)
print(f'Ordem alfabética dos times: {sorted(tabelaTimes)}')
print('=-='*20)
print('O time do Corinthians está na {}° posição.'.format(tabelaTimes.index('Corinthians')+1))
print('=-='*20)
